### ISSUE TITLE
Route short name in DELFI data is long

### ISSUE THREAD

**Issue by jheubuch** [public-transport/transitous#1547]
Hi,

first of all thank you for making international routing this easy.
Since you added a script that adds the train numbers to DELFI departures, it occurs that the `routeShortName` is very long (consisting the line name AND the train number)

<img width="344" height="84" alt="Image" src="https://github.com/user-attachments/assets/586d4968-5c6e-474e-b4e1-49e435e5d9bc" />

In my opinion, it would be better to leave the `routeShortName` just with the line name because the full name is already displayed in `displayName`

Thank you in advance!

**Comment by felixguendling** [comment]
The script is here: https://github.com/public-transport/transitous/blob/main/scripts/de-DELFI.lua
It does not change `routeShortName`. If you use `/v4` the `routeShortName` is exactly what is in the data.

**Comment by traines-source** [comment]
There is actually a bug in the API versioning, meaning that certain endpoints would return the same (long `routeShortName`) as versions prior to `/v4`. We'll fix it in an upcoming release.

**Comment by traines-source** [comment]
This fix is deployed by now.

**Comment by jheubuch** [comment]
On `api/v2/trip` I still get the long name in `routeShortName` - is this intentional?

<img width="362" height="80" alt="Image" src="https://github.com/user-attachments/assets/e78828e1-24ef-4fe9-b890-a12dd8e188a7" />

**Comment by traines-source** [comment]
I think so, yes, because we figured that writing the displayName into routeShortName in versions prior to v4 ensures backwards compatibility in a better way than writing the actual routeShortName, because this might be empty. In theory we could probably with some work emulate the exact previous behaviour of falling back to tripShortName etc. But I'd just recommend upgrading to v4+ if you want to get the actual routeShortName from the feed.
